/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacao;

import dao.DAOIngrediente;
import dao.DAOPrato;
import dao.DAORefeicao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Ingrediente;
import modelo.Prato;
import modelo.Refeicao;

/**
 *
 * @author Roberto
 */
public class frmNovaRefeicao extends javax.swing.JFrame {

    /**
     * Creates new form frmNovaRefeicao
     */
    Refeicao refeicao;
    DefaultTableModel modeloPratos, modeloStatus;
    DAOPrato daoPrato = dao.DAOFactory.criaDAOprato();
    DAOIngrediente daoIng = dao.DAOFactory.criaDAOing();
    DAORefeicao daoRef = dao.DAOFactory.criaDAOref();
    boolean verifica = false;
    private boolean carregandoTabela = false;

    public frmNovaRefeicao() {
    initComponents();
    modeloPratos = (DefaultTableModel) listapratos.getModel();
    modeloStatus = (DefaultTableModel) statusref.getModel();

    // Listener para monitorar mudanças nas células da tabela
    modeloPratos.addTableModelListener(new javax.swing.event.TableModelListener() {
        @Override
        public void tableChanged(javax.swing.event.TableModelEvent e) {
            // Ignora a execução se a tabela estiver sendo montada via código
            if (carregandoTabela) return;

            // Verifica se foi uma atualização de célula
            if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
                int row = e.getFirstRow();
                int column = e.getColumn();

                // Índice 4 corresponde à coluna "pronto"
                if (column == 4 && row >= 0 && refeicao != null) {
                    Boolean isPronto = (Boolean) modeloPratos.getValueAt(row, column);
                    Prato prato = refeicao.getPratos().get(row);

                    if (isPronto) {
                        for (Ingrediente ingrediente : prato.getIngredientes()) {
                            
                            daoIng.devolverIngrediente(ingrediente);
                        }
                    } else {
                        for (Ingrediente ingrediente : prato.getIngredientes()) {
                            daoIng.retirarIngrediente(ingrediente);
                        }
                    }
                }
            }
        }
    });
}
    public frmNovaRefeicao(Refeicao refeicao) {
        System.out.println(refeicao.getId());
        this();
        if (refeicao != null) {
            this.refeicao = refeicao;

            // Preenche os campos de texto se o objeto refeicao não for nulo
            tempofield.setText(String.valueOf(refeicao.getTempoMaximo()));
            caloriafield.setText(String.valueOf(refeicao.getCaloriaMax()));
            componentefield.setText(String.valueOf(refeicao.getComponentes()));
        }
        preencherTabelas();
        verifica = true;
    }
private void preencherTabelas() {
    carregandoTabela = true; // Desativa a execução do listener
    try {
        modeloPratos.getDataVector().clear();
        modeloStatus.getDataVector().clear();
        
        for (Prato prato : refeicao.getPratos()) {
            modeloPratos.addRow(new Object[]{
                prato.getNome(),
                prato.getPorcoes(),
                prato.getCalorias(),
                prato.getTempo(),
                prato.isPronto()
            });
        }
        
        modeloStatus.addRow(new Object[]{refeicao.getTempoTtl(), refeicao.getCaloriaTtl()});
    } finally {
        carregandoTabela = false; // Reativa o listener para edições manuais do usuário
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tempofield = new javax.swing.JTextField();
        caloriafield = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        statusref = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listapratos = new javax.swing.JTable();
        btnPreparo = new javax.swing.JButton();
        btnAceitar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        componentefield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tempo Maximo:");

        jLabel2.setText("Calorias Maximas");

        tempofield.setColumns(15);

        caloriafield.setColumns(15);

        statusref.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tempo", "Calorias"
            }
        ));
        jScrollPane1.setViewportView(statusref);

        listapratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "porções", "calorias", "tempo", "pronto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listapratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listapratosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listapratos);

        btnPreparo.setText("Preparar Refeição");
        btnPreparo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreparoActionPerformed(evt);
            }
        });

        btnAceitar.setText("Aceitar");
        btnAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceitarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel3.setText("Numero De pratos");

        componentefield.setColumns(15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caloriafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tempofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(componentefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceitar)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnPreparo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tempofield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(componentefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(caloriafield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPreparo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceitar)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreparoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreparoActionPerformed
        try {
            // 1. Converte o texto dos campos para inteiro
            int tempoMaximo = Integer.parseInt(tempofield.getText().trim());
            String caloriaTexto = caloriafield.getText().trim();
            int caloriaMax = caloriaTexto.isEmpty() ? 0 : Integer.parseInt(caloriaTexto);
            int componentes = Integer.parseInt(componentefield.getText().trim());

            // 2. Validação para impedir valores <= 0
            if (tempoMaximo <= 0 || componentes <= 0) {
                JOptionPane.showMessageDialog(this,
                        "Tempo, número de pratos e calorias devem ser valores positivos.",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return; // STOP: Interrompe a execução para não criar a refeição inválida
            }

            // 3. Cria e prepara a refeição
            System.out.println("Caloria " + caloriaMax);

            Refeicao novaRefeicao = new Refeicao(tempoMaximo, componentes, caloriaMax);
            List<Prato> menu = daoPrato.listar();
            List<Ingrediente> dispensa = daoIng.listar();
            novaRefeicao.prepararRefeicao(menu, dispensa);
            if (refeicao != null) {
                novaRefeicao.setId(refeicao.getId());
            }
            this.refeicao = novaRefeicao;
            JOptionPane.showMessageDialog(this, "Refeição gerada com sucesso!");
            preencherTabelas();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, preencha todos os campos apenas com números inteiros válidos.",
                    "Erro de Digitação",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao preparar refeição: " + e.getMessage());
        }

    }//GEN-LAST:event_btnPreparoActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new frmPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceitarActionPerformed
        if (this.verifica) {

            int verific = daoRef.editar(refeicao);
            if (verific > 0) {

                new frmPrincipal().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao editar refeição");
            }
        } else {
            int verific = daoRef.inserir(refeicao);
            if (verific > 0) {

                new frmPrincipal().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao inserir refeição");
            }
        }
    }//GEN-LAST:event_btnAceitarActionPerformed

    private void listapratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listapratosMouseClicked
      if (evt.getClickCount() > 1) {
            int linha = listapratos.getSelectedRow();
            Prato p=refeicao.getPratos().get(linha);
            
            
            new frmPrato(p).setVisible(true);

        }
    }//GEN-LAST:event_listapratosMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceitar;
    private javax.swing.JButton btnPreparo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField caloriafield;
    private javax.swing.JTextField componentefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listapratos;
    private javax.swing.JTable statusref;
    private javax.swing.JTextField tempofield;
    // End of variables declaration//GEN-END:variables
}
