/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplicacao;

import dao.DAOIngrediente;
import dao.DAORefeicao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Ingrediente;
import modelo.Refeicao;

/**
 *
 * @author Azurha
 */
public class frmPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmPrincipal.class.getName());
    private DefaultTableModel modeloRef = null;
    private DefaultTableModel modeloDis = null;
    private DAORefeicao daoRef = dao.DAOFactory.criaDAOref();
    private DAOIngrediente daoIng = dao.DAOFactory.criaDAOing();

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        modeloRef = (DefaultTableModel) tblRef.getModel();
        modeloDis = (DefaultTableModel) tblDis.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PainelRef = new javax.swing.JLayeredPane();
        btnsair = new javax.swing.JButton();
        BotaoNovo = new BotaoRedondo("+");
        btnApagar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRef = new javax.swing.JTable();
        PainelDispensa = new javax.swing.JLayeredPane();
        btnSair = new javax.swing.JButton();
        btnApagarIng = new javax.swing.JButton();
        BotaoNovoIng = new BotaoRedondo("+");
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDis = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        PainelRef.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PainelRefFocusGained(evt);
            }
        });
        PainelRef.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsair.setText("Sair");
        btnsair.addActionListener(this::btnsairActionPerformed);
        PainelRef.add(btnsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        BotaoNovo.setBackground(new java.awt.Color(24, 121, 24));
        BotaoNovo.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        BotaoNovo.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovo.setText("+");
        BotaoNovo.setAlignmentY(0.0F);
        BotaoNovo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotaoNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoNovo.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BotaoNovo.setMaximumSize(new java.awt.Dimension(50, 50));
        BotaoNovo.setMinimumSize(new java.awt.Dimension(50, 50));
        BotaoNovo.addActionListener(this::BotaoNovoActionPerformed);
        PainelRef.setLayer(BotaoNovo, javax.swing.JLayeredPane.MODAL_LAYER);
        PainelRef.add(BotaoNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 40, 40));

        btnApagar.setText("Apagar");
        btnApagar.addActionListener(this::btnApagarActionPerformed);
        PainelRef.add(btnApagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        tblRef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Pratos", "Tempo", "Calorias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRefMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblRef);

        PainelRef.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, 0, 890, 540));

        jTabbedPane1.addTab("Refeições", PainelRef);

        PainelDispensa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);
        PainelDispensa.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        btnApagarIng.setText("Apagar");
        btnApagarIng.addActionListener(this::btnApagarIngActionPerformed);
        PainelDispensa.add(btnApagarIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        BotaoNovoIng.setBackground(new java.awt.Color(24, 121, 24));
        BotaoNovoIng.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        BotaoNovoIng.setForeground(new java.awt.Color(255, 255, 255));
        BotaoNovoIng.setText("+");
        BotaoNovoIng.setAlignmentY(0.0F);
        BotaoNovoIng.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotaoNovoIng.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotaoNovoIng.setMargin(new java.awt.Insets(0, 0, 0, 0));
        BotaoNovoIng.setMaximumSize(new java.awt.Dimension(50, 50));
        BotaoNovoIng.setMinimumSize(new java.awt.Dimension(50, 50));
        BotaoNovoIng.addActionListener(this::BotaoNovoIngActionPerformed);
        PainelDispensa.setLayer(BotaoNovoIng, javax.swing.JLayeredPane.MODAL_LAYER);
        PainelDispensa.add(BotaoNovoIng, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 40, 40));

        tblDis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nome", "grupo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDis);

        PainelDispensa.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 540));

        jTabbedPane1.addTab("dispensa", PainelDispensa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoActionPerformed
        new frmNovaRefeicao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoNovoActionPerformed

    private void PainelRefFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PainelRefFocusGained
    }//GEN-LAST:event_PainelRefFocusGained

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        PreencherTabelaRef();
        PreencherTabelaDis();
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void tblRefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRefMouseClicked
        if (evt.getClickCount() > 1) {
            int linha = tblRef.getSelectedRow();
            int id = Integer.parseInt(modeloRef.getValueAt(linha, 0).toString());
            Refeicao refeicao = daoRef.buscar(id);
            new frmNovaRefeicao(refeicao).setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_tblRefMouseClicked

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        int linha = tblRef.getSelectedRow();
        if (linha >= 0) {
            int id = (int) modeloRef.getValueAt(linha, 0);
            daoRef.apagar(id);
            PreencherTabelaRef();
        } else {
            JOptionPane.showMessageDialog(this, "Linha invalida");
        }
    }//GEN-LAST:event_btnApagarActionPerformed

    private void BotaoNovoIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoNovoIngActionPerformed
        new frmNovoIngrediente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoNovoIngActionPerformed

    private void btnApagarIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarIngActionPerformed
       int linha = tblDis.getSelectedRow();
        if (linha >= 0) {
            int id = (int) modeloDis.getValueAt(linha, 0);
            daoIng.apagar(id);
            PreencherTabelaDis();
        } else {
            JOptionPane.showMessageDialog(this, "Linha invalida");
        }
              
    }//GEN-LAST:event_btnApagarIngActionPerformed

    private void tblDisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDisMouseClicked
        if (evt.getClickCount() > 1) {
            int linha = tblDis.getSelectedRow();
            int id = Integer.parseInt(modeloDis.getValueAt(linha, 0).toString());
            Ingrediente ingrediente = daoIng.buscar(id);
            new frmNovoIngrediente(ingrediente).setVisible(true);
            this.dispose();

        }
    }//GEN-LAST:event_tblDisMouseClicked

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int opcao = JOptionPane.showConfirmDialog(
        this, 
        "Deseja realmente parar a execução?", 
        "Confirmação", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    if (opcao == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
                int opcao = JOptionPane.showConfirmDialog(
        this, 
        "Deseja realmente parar a execução?", 
        "Confirmação", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE
    );

    if (opcao == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_btnsairActionPerformed
    private void PreencherTabelaRef() {
        modeloRef.getDataVector().clear();
        try {
            for (Refeicao refeicao : daoRef.listar()) {
                modeloRef.addRow(new Object[]{refeicao.getId(),
                    refeicao.getComponentes(),
                    refeicao.getTempoTtl(),
                    refeicao.getCaloriaTtl()

                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void PreencherTabelaDis() {
        modeloDis.getDataVector().clear();
        try {
            for (Ingrediente ingrediente : daoIng.listar()) {
                modeloDis.addRow(new Object[]{
                    ingrediente.getId(),
                    ingrediente.getNome(),
                    ingrediente.getGrupo().getNome(),
                    ingrediente.getQuantidade()
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            throw new RuntimeException("Erro " + e.getMessage(), e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmPrincipal().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoNovo;
    private javax.swing.JButton BotaoNovoIng;
    private javax.swing.JLayeredPane PainelDispensa;
    private javax.swing.JLayeredPane PainelRef;
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnApagarIng;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnsair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblDis;
    private javax.swing.JTable tblRef;
    // End of variables declaration//GEN-END:variables
}
